### PR TITLE
Ensure Kotlin compilation task reruns when detekt config changes

### LINKED ISSUE #16: detekt analysis doesn't run when changing config after clean compile
What happens:
* Run compile Kotlin task with `allWarningsAsErrors = true`: FAIL
  * detekt identifies issues
  * Fix issues
* Run compile Kotlin task with `allWarningsAsErrors = true`: SUCCESS
* Change detekt config - enable new rules that should fail build
* Run compile Kotlin task with `allWarningsAsErrors = true`: SUCCESS

What should happen:
* Run compile Kotlin task with `allWarningsAsErrors = true`: FAIL
  * detekt identifies issues
  * Fix issues
* Run compile Kotlin task with `allWarningsAsErrors = true`: SUCCESS
* Change detekt config - enable new rules that should fail build
* Run compile Kotlin task with `allWarningsAsErrors = true`: FAIL
  * detekt identifies issues
  * Fix issues

Why? Because the subplugin input is the config file path(s), the compiler is not aware of the config file contents, so it will not rerun the compilation if the config file contents change.

Probably calculating hash value for the config file content passed in and providing that as a compiler input will fix this, since the hash will change when the config file content changes.

### PR DESCRIPTION
**Pull request by 3flex**
Fixes #16 

This is definitely a bit of a hack, but until KT-41711 is resolved, I can't see a better option. I think the compiler plugin needs this feature because behaviour is surprising otherwise - you would reasonably expect a config file change would take effect the next time a compilation task is run.

### CODE REVIEW

**Review by schalkms — APPROVED** [review]

**Review by arturbosch — APPROVED** [review]

File: src/main/kotlin/io/github/detekt/gradle/DetektKotlinCompilerPlugin.kt [hunk 1]
```diff
@@ -36,6 +41,17 @@ class DetektKotlinCompilerPlugin : KotlinCompilerPluginSupportPlugin {
         return options
     }
 
+    private fun ConfigurableFileCollection.toDigest(): String {
```
Comment (arturbosch) [inline src/main/kotlin/io/github/detekt/gradle/DetektKotlinCompilerPlugin.kt:44]: Could you add a testcase for this isolated function if you have time, please?

Comment (3flex) [reply src/main/kotlin/io/github/detekt/gradle/DetektKotlinCompilerPlugin.kt]: I've added a test - please merge if everything looks OK

File: src/main/kotlin/io/github/detekt/gradle/DetektKotlinCompilerPlugin.kt [hunk 2]
```diff
@@ -43,3 +48,14 @@ class DetektKotlinCompilerPlugin : KotlinCompilerPluginSupportPlugin {
...
 }
+
+internal fun ConfigurableFileCollection.toDigest(): String {
+    val concatenatedConfig = this
+        .filter { it.isFile }
+        .map(File::readBytes)
+        .fold(byteArrayOf()) { acc, file -> acc + file }
+
+    return Base64.getEncoder().encodeToString(
+        MessageDigest.getInstance("SHA-256").digest(concatenatedConfig)
```
Comment (BraisGabin) [inline src/main/kotlin/io/github/detekt/gradle/DetektKotlinCompilerPlugin.kt:59]: We could use `DigestInputStream` or something similar so we don't need to copy all the file in memory to compute the sha. But thinking about what detekt and the Compiler does this is clearly nothing so 🤐.

**Review by BraisGabin — APPROVED** [review]
